# Generated by Django 3.1.4 on 2021-03-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject_code',
        ),
    ]
