# Generated by Django 3.1.4 on 2021-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20210306_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='exam',
            field=models.CharField(choices=[('Internal-1', 'I1'), ('Internal-2', 'I2'), ('Internal', 'I')], max_length=25, verbose_name='Exam Name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.CharField(blank=True, max_length=5, verbose_name='Marks'),
        ),
    ]
