# Generated by Django 3.1.4 on 2021-03-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20210317_2153'),
        ('students', '0018_auto_20210314_1941'),
    ]

    operations = [
    ]
