# Generated by Django 3.1.4 on 2021-03-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20210318_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='branch',
            field=models.CharField(choices=[('01', 'Computer Engineering'), ('02', 'Information Technology')], max_length=70, verbose_name='Branch'),
        ),
    ]
