# Generated by Django 3.1.4 on 2021-03-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20210318_1645'),
        ('common', '0015_auto_20210317_1142'),
        ('students', '0022_auto_20210318_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[(1, 'Present'), (0, 'Absent')], max_length=10, verbose_name='Status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
