# Generated by Django 3.1.4 on 2021-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20210405_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='branch',
            field=models.CharField(choices=[('01', 'Computer Engineering'), ('02', 'Information Technology')], max_length=70, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('01', 'Computer Engineering'), ('02', 'Information Technology')], max_length=70, verbose_name='Branch'),
        ),
    ]
