# Generated by Django 3.1.4 on 2021-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_auto_20210406_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment', models.CharField(max_length=70, verbose_name='Enrolment Number')),
                ('doubt', models.CharField(max_length=500, verbose_name='Doubt')),
                ('answer', models.CharField(blank=True, max_length=500, verbose_name='Answer')),
            ],
        ),
    ]
