# Generated by Django 3.1.4 on 2021-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20210407_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='course_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
