# Generated by Django 3.1.4 on 2021-02-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20210131_1406'),
        ('staff', '0020_auto_20210131_1139'),
    ]

    operations = [
    ]
