# Generated by Django 3.1.4 on 2021-02-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20210206_1854'),
        ('staff', '0021_merge_20210210_0652'),
    ]

    operations = [
    ]
