# Generated by Django 3.1.4 on 2021-01-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210122_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('subject_code', models.CharField(max_length=15, verbose_name='Subject Code')),
                ('description', models.TextField(default='', max_length=300, verbose_name='Description')),
                ('semester', models.CharField(max_length=2, verbose_name='Semester')),
                ('branch', models.CharField(default='', max_length=70, verbose_name='Branch')),
                ('course_credits', models.CharField(default=0, max_length=3, verbose_name='Course Credits')),
                ('course_type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Elective', 'Elective')], default='Mandatory', max_length=20)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(default='', max_length=30, verbose_name='Faculty ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
            ],
        ),
    ]
