# Generated by Django 3.1.4 on 2021-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210122_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
    ]
