# Generated by Django 3.1.4 on 2021-02-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210205_1701'),
        ('common', '0009_course_coursefaculty'),
    ]

    operations = [
    ]
