# Generated by Django 3.1.4 on 2021-02-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_merge_20210210_0652'),
        ('common', '0010_merge_20210205_1809'),
    ]

    operations = [
    ]
