# Generated by Django 3.1.4 on 2021-03-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20210303_1052'),
        ('common', '0011_merge_20210210_0849'),
    ]

    operations = [
    ]
