# Generated by Django 3.1.4 on 2021-04-05 11:58

import common.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20210405_1728'),
        ('common', '0015_auto_20210317_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('submission_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Submission Time')),
                ('submission_file', models.FileField(blank=True, upload_to='submissions', validators=[common.validators.validate_file_extension], verbose_name='Submission File')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.assignment', verbose_name='Assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
            ],
        ),
    ]
