# Generated by Django 3.1.4 on 2021-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description'),
        ),
    ]
